<?php 
$countPost = count( $this->posts );
/*
if( !Session::get( 'authenticated' ) ) :
	
	header( 'location: '.URL_BASE );
	exit;
	
endif;
*/ 
include 'views/inc/header.php'; ?>

<style>
	
	body
	{
		background-position: <?php echo $this->infoSession->bg_position; ?> 55px;
		background-attachment: <?php echo $this->infoSession->bg_attachment; ?>;
		
		<?php if( $this->infoSession->bg_attachment == 'fixed' ): ?>
		background-repeat: repeat repeat; 
		<?php else: ?>
		background-repeat: no-repeat; 
		<?php endif; ?>
		
		background-color: <?php echo $this->infoSession->bg_color; ?>;
		
		<?php if( $this->infoSession->bg != '' ): ?>
		background-image: url(<?php echo URL_BASE.'public/backgrounds/'.$this->infoSession->bg; ?>);
		<?php endif; ?>
	}
	<?php include('views/inc/ios_background.php'); ?>
	
	body a,
	body a:hover { color: <?php echo $this->infoSession->color_link; ?>; }
	
	.icons { background-color: <?php echo $this->infoSession->color_link; ?>;}
</style>


<link href="<?php echo $_layoutParams['root_css']; ?>colorbox.css" rel="stylesheet" />
</head>
<!-- Body -->
	<body data-max="<?php echo MAX_LENGTH; ?>">
		
	<?php include 'views/inc/navigation.php'; ?>	
			
	 <!-- container -->  
    <div class="container container-auth">
    	
    	<!-- row -->  
    	<div class="row col-pb">
     
	
	<div class="col-md-8">
				
		<div class="panel panel-default panel-live">
			
			<div class="panel-heading grid-panel-title">
    <h3 class="panel-title titleBar"><?php echo $this->titleSort.$_SESSION['LANG']['discover']; ?></h3>
  </div>
  
   <button type="button" class="btn btn-info btn-border btn-df btn-sm btn-block margin-bt news_post"></button>

<div class="posts">
				
				<div class="loading-bar load"></div>
				
		<?php if( $this->$countPost == 0 ): ?>
		
			<div class="panel-footer notfound text-center" style="display: none;">
				<?php echo $_SESSION['LANG']['no_results']; ?>
			</div>
		<?php endif; ?>
</div><!-- posts -->
</div>
</div><!--/col-md-* -->
 			
		     <!-- col-md-* -->  
		     <div class="col-md-4">
		     	
			<div class="popout"></div>
			
	<button type="button" class="btn btn-info btn-block btn-border btn-lg show-toogle" data-toggle="collapse" data-target=".navleft-collapse">
		   <i class="fa fa-bars"></i>
		</button>
		
		<div class="collapsexxx navleft-collapse">
			
			<div class="list-group">
     	  
		  <!-- **** list-group-item **** -->	
		  <a href="<?php echo URL_BASE; ?>discover/"  class="list-group-item <?php if( !isset( $this->query_sql_ajax ) ) { echo 'active'; } ?>">
		  	<span class="icon-newspaper myicon-right"></span> <?php echo $_SESSION['LANG']['all']; ?>
		  	
		  	<span class="pull-right">
			  		<i class="fa fa-chevron-right "></i>
			  	</span>
		  	</a><!-- **** ./ list-group-item **** -->
		  	
		  	<!-- **** list-group-item **** -->	
		  <a href="<?php echo URL_BASE; ?>discover/?sort=photos"  class="list-group-item <?php if( $_GET['sort'] == 'photos'  ) { echo 'active'; } ?>">
		  	<span class="glyphicon glyphicon-picture myicon-right"></span> <?php echo $_SESSION['LANG']['photos']; ?>
		  	
		  	<span class="pull-right">
			  		<i class="fa fa-chevron-right "></i>
			  	</span>
		  	</a><!-- **** ./ list-group-item **** -->	
		  	
		  	<!-- **** list-group-item **** -->	
		  <a href="<?php echo URL_BASE; ?>discover/?sort=videos"  class="list-group-item <?php if( $_GET['sort'] == 'videos'  ) { echo 'active'; } ?>">
		  	<span class="fa fa-youtube-play myicon-right"></span> <?php echo $_SESSION['LANG']['videos']; ?>
		  	
		  	<span class="pull-right">
			  		<i class="fa fa-chevron-right "></i>
			  	</span>
		  	</a><!-- **** ./ list-group-item **** -->
		  	
		  	<!-- **** list-group-item **** -->	
		  <a href="<?php echo URL_BASE; ?>discover/?sort=music"  class="list-group-item <?php if( $_GET['sort'] == 'music'  ) { echo 'active'; } ?>">
		  	<span class="fa fa-music myicon-right"></span> <?php echo $_SESSION['LANG']['music']; ?>
		  	
		  	<span class="pull-right">
			  		<i class="fa fa-chevron-right "></i>
			  	</span>
		  	</a><!-- **** ./ list-group-item **** -->	
		  	
		  	<!-- **** list-group-item **** -->	
		  <a href="<?php echo URL_BASE; ?>discover/?sort=links"  class="list-group-item <?php if( $_GET['sort'] == 'links'  ) { echo 'active'; } ?>">
		  	<span class="fa fa-link myicon-right"></span> <?php echo $_SESSION['LANG']['links']; ?>
		  	
		  	<span class="pull-right">
			  		<i class="fa fa-chevron-right "></i>
			  	</span>
		  	</a><!-- **** ./ list-group-item **** -->
	
		</div><!-- * list-group * -->
			
			<?php 
				   //<---- * advertising * --->
				   include 'views/inc/advertising.php';
				   //<---- * who_follow * --->
				   include 'views/inc/who_to_follow.php';
				   //<---- * trending * --->
				   include 'views/inc/trending.php'; 
				   //<---- * Footer * --->
				   include 'views/inc/footer_session.php';
				   
				 ?>
				 
				 </div><!-- navleft-collapse -->
	
	</div><!--/col-md-* -->
			
		</div><!-- *** row *** -->
	</div><!-- **************** container **************** -->

   
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.easing.1.3.js"></script>
    <script src="<?php echo $_layoutParams['root_js']; ?>jquery-ui-1.10.3.custom.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.ui.touch-punch.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>bootstrap.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>bootstrap-switch.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.autosize.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>functions.js?5"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>count.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>add.post.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.form.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>timeago/jqueryTimeago_<?php echo $_SESSION['lang']; ?>.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.colorbox.js"></script>
      <script src="https://unpkg.com/smartphoto@1.1.0/js/jquery-smartphoto.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.scroll.user.js?4"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>discover.timeline.js?4"></script>
  
   <script src="/public/reactions/assets/js/script.js?v20241115"></script>

   <?php if( !Session::get( 'authenticated' ) ) : ?>
   <script src="<?php echo $_layoutParams['root_js']; ?>login.sign.up.js"></script>
   <?php endif; ?>
   
   <script type="text/javascript">
   
   var sortAjax = '<?php echo $this->query_sql_ajax; ?>';

   $(".galeryAjax").colorbox({
   	fixed: false,
   	maxHeight: 550
   	});
   	
   	//=== COUNTER
	$(document).on('mouseenter','#reply_post', function(event){

   		 if ($(this).data('hascharcount') == undefined) {
			$(this).data('hascharcount', true).charCount({ allowed: <?php echo MAX_LENGTH; ?>, warning: 10 });
		}
		
   	});
   
   $('.posts').scrollPagination({
		nop     : 10,
		offset  : 0,
		error   : '',
		delay   : 500,
		              
		scroll  : true, 
		query   : 0,
		file    : 'ajax.discover.php',
		_userId : '<?php echo $this->query_sql_ajax; ?>',
		totalGlobal : <?php echo $countPost; ?>
	});


//Header Hide when scroll
var menuHeight = $("#menu-wrap").height();
var startPos = 0;
$(window).scroll(function(){
  var currentPos = $(this).scrollTop();
  if (currentPos > startPos) {
    if($(window).scrollTop() >= 1) {
      $("#menu-wrap").css("top", "-" + ($(window).scrollTop() - 1) + "px");
//		$("menu-wrap").fadeOut();
	}
  } else {
    $("#menu-wrap").css("top", 0 + "px");
//	  $("menu-wrap").fadeIn();
  }
  startPos = currentPos;
});
	   
   <?php if( !Session::get( 'authenticated' ) and Session::get( 'last_regnav_open' )<(time()-1800) ) : ?>
  $('#regnavmenu').addClass('open');
   <?php 
   $_SESSION['last_regnav_open']=time();
   endif; ?>
  </script>
	</body>
</html>
