<?php 
//<--- * User * ---> 
$count = count( $this->data );

//<--- * Last Photos * --->
$countMedia = count( $this->_media );

if( isset( $this->data ) &&  $count != 0 && $this->checkBlocked[0]['status'] != 1 ) :

?>
<?php include 'views/inc/header.php'; ?>
<link rel="canonical" href="<?php echo URL_BASE.$this->info->username.'/media' ?>">
<style>
	
	body
	{
		background-position: <?php echo $this->info->bg_position; ?> 55px;
		background-attachment: <?php echo $this->info->bg_attachment; ?>;
		
		<?php if( $this->info->bg_attachment == 'fixed' ): ?>
		background-repeat: repeat repeat; 
		<?php else: ?>
		background-repeat: no-repeat; 
		<?php endif; ?>
		
		background-color: <?php echo $this->info->bg_color; ?>;
		
		<?php if( $this->info->bg != '' ): ?>
		background-image: url(<?php echo URL_BASE.'public/backgrounds/'.$this->info->bg; ?>);
		<?php endif; ?>
	}
	<?php include('views/inc/ios_background.php'); ?>
	
	body a,
	body a:hover { color: <?php echo $this->info->color_link; ?>; }
	.icons { background-color: <?php echo $this->info->color_link; ?>;}
	.container_data_profile a:hover span{ color: <?php echo $this->info->color_link; ?>;  }
	
	/* PopOut Message User */
	#container_popout_message { display: none; width: 100%; height: 100%; background: #000; opacity: 0.8; position: fixed; z-index: 9999;  }
	.popoutUser_message     { top: 20%; -webkit-box-shadow: 0 0 10px #1F1E1E; box-shadow: 0 0 10px #1F1E1E; display: none; max-width: 550px; padding: 0; background:#F8F8F8; color: #999; font-size: 12px; 
	border-radius: 4px; -webkit-border-radius: 4px; position: fixed;  z-index: 10000; overflow: hidden; width: 80.857%; text-align: center; font-weight: bold; }
	/* top: 20%; */
	.wrap_popout_message { width: 100%; overflow: hidden; display: block; }
	.title_popout_message { -webkit-box-shadow: inset 0 -10px 20px #F3F3F3; box-shadow: inset 0 -10px 20px #F3F3F3; background: #ececec; color: #333; border-bottom: 1px solid #DDD; height: 35px; }
	.close_popout_message { position: absolute; right: 0; opacity: 0.7; width: 22px; height: 22px; margin-top: 5px; margin-right: 10px; background : url('<?php echo $_layoutParams['root_img']; ?>close.png') no-repeat; float: right; cursor: pointer;  }
	.close_popout_message:hover { opacity: 1; }
	.content_user_message {  width: 100%; float: left; padding: 0 0 10px 0; }
	.textPopout_message { width: 100%; font-size: 12px; color: #414141; float: left; display: block; padding: 0; line-height: 35px; }

</style>
<link href="<?php echo $_layoutParams['root_css']; ?>colorbox.css" rel="stylesheet" />
</head>
	<!-- Body -->
	<body data-max="<?php echo MAX_LENGTH; ?>">
		<?php include 'views/inc/profile_summary_inc.php'; ?>
		
		<!-- PopOut Message User -->
	<div id="container_popout_message"></div>
		<div class="popoutUser_message" id="content_popout_message">
			<div class="wrap_popout_message">
				<div class="title_popout_message">
					<span class="textPopout_message"></span>
					<div class="close_popout_message"></div>
				</div>
				<div class="content_user_message">
				</div><!-- content user -->
			</div><!-- wrap popout -->
		</div>
	<!-- Message user -->
	
		<!-- warpper_top_bar -->
		<div class="warpper_top_bar">
				<!-- inner_top_bar -->
				<header class="inner_top_bar">
					<!-- padding_class -->
					<div class="padding_class">
						<a href="<?php echo URL_BASE; ?>">
							<?php include 'views/inc/logo.php'; ?>
						</a>
					
					<?php include 'views/inc/navigation.php'; ?>
			    </div><!-- padding_class -->
			</header><!-- inner_top_bar -->
		</div><!-- warpper_top_bar -->
	
	<!-- page -->
	<div class="page">
		<!-- layout -->
		<section class="layout session">
			<div class="popout"></div>
			<!-- padding_class -->
		    <div class="padding_class sessionClass">
		    	<div class="formSearchResp">
						   <form action="search/" class="formResponsive" method="get" id="search_engine" accept-charset="UTF-8">
							  <input id="btnItems" name="q" class="mention" type="text" placeholder="<?php echo $_SESSION['LANG']['search_word']; ?>" maxlength="100">	
						      </form>
					</div>
		    <!-- wrapper_grid -->
		     <div class="wrapper_grid floatLeft">
				   
				<?php 
				   //<---- * advertising * --->
				   include 'views/inc/advertising.php';
				   if( Session::get( 'authenticated' ) ) :
					   //<---- * who_follow * --->
				      include 'views/inc/who_to_follow.php';
					   endif;
				   
				   //<---- * trending * --->
				   include 'views/inc/trending.php'; 
				    ?>
				   
				    <!-- Grid 1 -->
				   <div class="grid_1">
				   		<!-- container_grid -->
				   		<div class="container_grid about_pages">
				   			<?php include 'views/inc/footer_session.php'; ?>
				   		</div><!-- container_grid -->
				   </div><!-- Grid 1 -->
				   
			   </div><!-- wrapper_grid -->
			   
			   
			   <!-- Grid 2 -->
			   <div class="grid_2 floatRight">
			   	
			   	<!-- nav_profile -->
		    	<div class="grid_profile">
		    		<!-- container_profile -->
				   		<div class="container_profile">
				   			<a href="<?php echo URL_BASE.$this->info->username; ?>">
				   				<img src="<?php echo URL_BASE.'public/avatar/'.$this->info->avatar; ?>"  class="avatar_large" />
				   				</a>
				   			<!-- profile detail -->
					   			<div class="profile_detail">
					   				<span class="detail_top" style="padding: 0; border: none;">
					   					<a href="<?php echo URL_BASE.$this->info->username; ?>">
					   						<h1><?php echo stripslashes( $this->info->name ); ?></h1> 
					   					</a>
					   					
					   					
					   					<?php if( $this->info->type_account == '1' ): ?>
					   					<img title="<?php echo $_SESSION['LANG']['verified']; ?>" class="verified_img west" src="<?php echo URL_BASE; ?>public/img/verified.png"> 
					   					<?php endif; ?>
					   					<?php if( $this->followActive->status == 1 ): ?>
					   					<span class="isFollow">FOLLOWS YOU</span>
					   					<?php endif;?>
					   				</span><!-- detail_top -->
					   			<ul class="user_data" style="padding: 0;">
					   				<strong style="color: #999; font-weight: normal; font-size: 14px;">@<?php echo $this->info->username; ?></strong>
					   			</ul>
					   				
					   			</div><!-- profile_detail -->
					   				
				   			</div><!-- container_profile -->
		    	</div><!-- nav_profile -->
		    	
		    	<h4 class="titleBar"><?php echo $_SESSION['LANG']['photos_videos']; ?>  // <?php echo $_SESSION['LANG']['media']; ?> </h4>
				<div style="overflow: hidden; padding: 15px;">
				<ul class="media_profile_media">
						
					</ul>
					</div><!-- DIV -->
		</div><!-- Grid 2 -->
			   		
			 </div><!-- padding_class -->
		</section><!-- layout -->
	</div><!-- page -->

   
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery-1.7.1.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.easing.1.3.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.placeholder.1.1.1.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery-ui-1.8.17.custom.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>functions.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>count.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>add.post.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.form.js"></script>
  <script src="<?php echo $_layoutParams['root_js']; ?>timeago/jqueryTimeago_<?php echo $_SESSION['lang']; ?>.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.colorbox.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.scroll.user.js"></script>
   
   <?php if( !Session::get( 'authenticated' ) ) : ?>
   <script src="<?php echo $_layoutParams['root_js']; ?>login.sign.up.js"></script>
   <?php endif; ?>
 	
 <script type="text/javascript">
 
 $(".media_galery").colorbox({
   	rel:'galery'
   	});
   	
   	<?php if( $countMedia != 0 ): ?> 
   $('.media_profile_media').scrollPagination({
		nop     : 25, 
		offset  : 0, 
		error   : '',
		delay   : 500,
		               
		scroll  : true, 
		query   : 0,
		file    :'get_all_media.php',
		_userId : <?php echo $this->info->id; ?>,
		totalGlobal :  <?php echo $countMedia; ?>
	});
	  <?php endif; ?> 
	  
	  
   jQuery(document).ready(function($) {
   //=== PLACEHOLDER	
  $(function(){
      $(':input[placeholder]').placeholder();
    });
	
   //====== TIME AGO
     
});//<-------- * DOM * ------>

  </script>

	</body>
</html>
  <?php
else:
	
	header ('HTTP/1.0 404 Not Found');
	include 'public/error/404.php'; // SHOW ERROR 404
	exit;
      
	endif;//<-- COUNT - 0 Result ?>
